package nvk.cotrip.ui.trip.form

import nvk.cotrip.R

enum class TripCurrency(
    val code: String,
    val symbol: String,
    val labelRes: Int,
) {
    EUR("EUR", "€", R.string.currency_eur),
    USD("USD", "$", R.string.currency_usd),
    GBP("GBP", "£", R.string.currency_gbp),
    JPY("JPY", "¥", R.string.currency_jpy),
    CNY("CNY", "¥", R.string.currency_cny),
    KRW("KRW", "₩", R.string.currency_krw),
    AUD("AUD", "$", R.string.currency_aud),
    CAD("CAD", "$", R.string.currency_cad),
    CHF("CHF", "CHF", R.string.currency_chf),
    SEK("SEK", "kr", R.string.currency_sek),
    NOK("NOK", "kr", R.string.currency_nok),
    DKK("DKK", "kr", R.string.currency_dkk),
    PLN("PLN", "zł", R.string.currency_pln),
    CZK("CZK", "Kč", R.string.currency_czk),
    HUF("HUF", "Ft", R.string.currency_huf),
    TRY("TRY", "₺", R.string.currency_try),
    ILS("ILS", "₪", R.string.currency_ils),
    AED("AED", "د.إ", R.string.currency_aed),
    SAR("SAR", "﷼", R.string.currency_sar),
    INR("INR", "₹", R.string.currency_inr),
    THB("THB", "฿", R.string.currency_thb),
    SGD("SGD", "$", R.string.currency_sgd),
    HKD("HKD", "$", R.string.currency_hkd),
    IDR("IDR", "Rp", R.string.currency_idr),
    MYR("MYR", "RM", R.string.currency_myr),
    PHP("PHP", "₱", R.string.currency_php),
    MXN("MXN", "$", R.string.currency_mxn),
    BRL("BRL", "R$", R.string.currency_brl),
    ARS("ARS", "$", R.string.currency_ars),
    CLP("CLP", "$", R.string.currency_clp),
    COP("COP", "$", R.string.currency_cop),
    ZAR("ZAR", "R", R.string.currency_zar),
    EGP("EGP", "£", R.string.currency_egp),
    RUB("RUB", "₽", R.string.currency_rub),
    UAH("UAH", "₴", R.string.currency_uah),
    KZT("KZT", "₸", R.string.currency_kzt),
    BYN("BYN", "Br", R.string.currency_byn),
}
