package nvk.cotrip.backend.ai

internal val illegalGoodsPhrases = listOf(
    "buy drugs",
    "sell drugs",
    "drug dealer",
    "cocaine",
    "heroin",
    "meth",
    "amphetamine",
    "marijuana",
    "weed",
    "cannabis club",
    "lsd",
    "ecstasy",
    "mdma",
    "opioid",
    "buy a gun",
    "gun shop",
    "firearm",
    "pistol",
    "rifle",
    "ammunition",
    "explosive",
    "bomb",
    "grenade",
    "fake passport",
    "fake id",
    "forged passport",
    "forged documents",
    "counterfeit visa",
    "stolen passport",
    "hack wifi",
    "hack wi fi",
    "steal password",
    "phishing",
    "malware",
    "ransomware",
    "ddos",
    "credit card fraud",
    "dark web",
    "купить наркотики",
    "наркотик",
    "кокаин",
    "героин",
    "метамфетамин",
    "марихуан",
    "пистолет",
    "оружие",
    "боеприпас",
    "бомба",
    "граната",
    "поддельный паспорт",
    "поддельный документ",
    "фальшивый паспорт",
    "взломать wifi",
    "взлом wifi",
    "фишинг",
    "вредонос",
    "даркнет",
)

internal val harmfulPhrases = listOf(
    "kill",
    "murder",
    "assault",
    "beat up",
    "stab",
    "attack people",
    "suicide",
    "self harm",
    "cut myself",
    "overdose",
    "rape",
    "sexual exploitation",
    "sex trafficking",
    "human trafficking",
    "underage sex",
    "child sexual",
    "harass",
    "bully",
    "hate crime",
    "terrorist",
    "terrorism",
    "убить",
    "убийств",
    "напасть",
    "избить",
    "самоубий",
    "селфхарм",
    "самоповреж",
    "изнасил",
    "сексуальн эксплуатац",
    "торговля людьми",
    "несовершеннолетн",
    "домогатель",
    "травля",
    "ненавист",
    "терроризм",
)

internal val metaResponsePhrases = listOf(
    "as an ai",
    "i can not",
    "i cannot",
    "i can't",
    "i do not have",
    "i don't have",
    "sorry",
    "unable to help",
    "need more info",
    "check online",
    "use google maps",
    "depends on your preferences",
    "как ии",
    "как ai",
    "я не могу",
    "у меня нет",
    "нужно больше информации",
    "проверьте онлайн",
    "посмотрите в google maps",
)

internal val offScopeSuggestionPhrases = listOf(
    "book a hotel",
    "book your flight",
    "travel insurance",
    "pack your bags",
    "buy a sim card",
    "exchange currency",
    "apply for a visa",
    "renew your passport",
    "check the weather",
    "generic sightseeing",
    "hotel check in",
    "airport transfer",
    "забронировать отель",
    "забронировать билет",
    "страховк",
    "собрать чемодан",
    "купить sim",
    "обменять валют",
    "оформить визу",
    "обновить паспорт",
    "проверить погоду",
    "трансфер из аэропорта",
)
