ktor {
  deployment {
    port = \\${?PORT}
  }
  application {
    modules = [ nvk.cotrip.backend.ApplicationKt.module ]
  }

  jwt {
    issuer = \\${?JWT_ISSUER}
    audience = \\${?JWT_AUDIENCE}
    realm = "cotrip"
    secret = \\${?JWT_SECRET}
  }

  db {
    url = \\${?DATABASE_URL}
    user = \\${?DATABASE_USER}
    password = \\${?DATABASE_PASSWORD}
    poolSize = 10
  }
}
