ktor {
  deployment {
    port = ${?PORT}
  }
  application {
    modules = [ nvk.cotrip.backend.ApplicationKt.module ]
  }

  jwt {
    issuer = ${?JWT_ISSUER}
    audience = ${?JWT_AUDIENCE}
    realm = "cotrip"
    secret = ${?JWT_SECRET}
  }

  db {
    url = ${?DATABASE_URL}
    user = ${?DATABASE_USER}
    password = ${?DATABASE_PASSWORD}
    poolSize = 10
  }

  invite {
    baseUrl = ${?INVITE_BASE_URL}
  }

  weather {
    openWeatherApiKey = ${?OPENWEATHER_API_KEY}
    refreshTtlHours = ${?WEATHER_REFRESH_TTL_HOURS}
  }

  devAuthEnabled = ${?DEV_AUTH_ENABLED}
}
